import WebHeader from "@/component/static/web/header";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function WebLayout({ children }) {
  return (
    <>
      <header><WebHeader /></header>
      <main>{children}</main>
      <footer>Footer</footer>
    </>
  );
}
