"use client";

import "@/public/css/globals.css";
import "react-toastify/dist/ReactToastify.css";
import FixMainHeight from "@/component/static/fixMainHeight";
import SetToast from "@/component/static/setToast";
import { SessionProvider } from "next-auth/react";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <body className="overflow-y-scroll">
        <SessionProvider>
          {children}
          <SetToast />
          <FixMainHeight />
        </SessionProvider>
      </body>
    </html>
  );
};

export default RootLayout;
