import "@/public/css/globals.css";
import "react-toastify/dist/ReactToastify.css";
import FixMainHeight from "@/component/static/fixMainHeight";
import { ToastContainer, toast } from "react-toastify";
import SetToast from "@/component/static/setToast";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <body className="overflow-scroll">
        {children}
        <SetToast />
        <FixMainHeight />
      </body>
    </html>
  );
};

export default RootLayout;
