import "@/public/css/globals.css";
import { FixMainHeight } from "@/component/static/fixMainHeight";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
        <FixMainHeight />
      </body>
    </html>
  );
}
