export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

const AuthLayout = ({ children }) => {
  return (
    <>
      <header>Header</header>
      <main>{children}</main>
      <footer>Footer</footer>
    </>
  );
};

export default AuthLayout;
