"use client";

import AuthHeader from "@/component/static/auth/header/header";
import AuthSideMenu from "@/component/static/auth/side/menu";
import { useSession } from "next-auth/react";
import { redirect, useRouter } from "next/navigation";
import { useEffect } from "react";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

const AuthLayout = ({ children }) => {
  const { data: session } = useSession();

  if (!session) {
    return redirect("/ingreso");
  }

  return (
    <>
      <div className="flex">
        <AuthSideMenu />
        <div className="relative w-full">
          <header>
            <AuthHeader />
          </header>
          <main>{children}</main>
          <footer>Footer</footer>
        </div>
      </div>
    </>
  );
};

export default AuthLayout;
