export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
  }
   
  export default function AuthLayout({ children }) {
    return (
       <>
         <header>Header</header>
         {children}
         <footer>Footer</footer>
       </>
     )
  }
  